#!/usr/bin/env python3
"""Regenerates the bundled station list from SomaFM's public listen page.

SomaFM's JSON API is closed to third parties, so the tool ships its own copy of
the station list, built from the "AAC PLS (SSL)" links that https://somafm.com/listen/
publishes for media players. Re-run this when SomaFM adds or renames a station:

    python3 scripts/update-stations.py            # fetches somafm.com/listen/
    python3 scripts/update-stations.py page.html  # or reads a saved copy
"""

import html
import re
import sys
import urllib.request
from pathlib import Path

LISTEN_URL = "https://somafm.com/listen/"
OUT = Path(__file__).resolve().parent.parent / "tool/src/main/kotlin/io/github/tthayer/somastreamer/Stations.kt"


def fetch(argv):
    if len(argv) > 1:
        return Path(argv[1]).read_text(encoding="utf-8")
    request = urllib.request.Request(LISTEN_URL, headers={"User-Agent": "SomaStreamer station list updater"})
    with urllib.request.urlopen(request, timeout=30) as response:
        return response.read().decode("utf-8")


def parse(page):
    stations = []
    # Each station block opens with "<!-- Channel: {id} Listeners: N -->".
    for block in re.split(r"<!-- Channel: ", page)[1:]:
        station_id = re.match(r"([a-z0-9]+)", block).group(1)
        title = re.search(r"<h3>(.*?)</h3>", block, re.S)
        genre = re.search(r"<!-- .+? \(([^)]*)\) -->", block)
        descr = re.search(r'<p class="descr">(.*?)</p>', block, re.S)
        aac = re.search(r"AAC PLS \(SSL\):(.*?)</nobr>", block, re.S)
        kbps = re.findall(r'href="/%s(\d+)\.pls"' % station_id, aac.group(1)) if aac else []
        if not title or not kbps:
            continue
        stations.append({
            "id": station_id,
            "title": clean(title.group(1)),
            "genre": clean(genre.group(1)) if genre else "",
            "description": clean(descr.group(1)) if descr else "",
            "kbps": [int(k) for k in kbps],
        })
    if not stations:
        sys.exit("no stations found; has the listen page layout changed?")
    return stations


def clean(text):
    return re.sub(r"\s+", " ", html.unescape(re.sub(r"<[^>]*>", "", text))).strip()


def kotlin_string(text):
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$") + '"'


def render(stations):
    rows = "\n".join(
        "    station({}, {}, {}, {}, {}),".format(
            kotlin_string(s["id"]),
            kotlin_string(s["title"]),
            kotlin_string(s["genre"]),
            kotlin_string(s["description"]),
            ", ".join(str(k) for k in s["kbps"]),
        )
        for s in stations
    )
    return f"""package io.github.tthayer.somastreamer

// GENERATED by scripts/update-stations.py from {LISTEN_URL}. Do not edit by hand.
// SomaFM's JSON API is closed to third parties; these are the public AAC .pls
// links SomaFM publishes for media players.

internal val SOMA_STATIONS: List<Channel> = listOf(
{rows}
)
"""


def main():
    stations = parse(fetch(sys.argv))
    OUT.write_text(render(stations), encoding="utf-8")
    print(f"wrote {len(stations)} stations to {OUT}")


if __name__ == "__main__":
    main()
